### ISSUE TITLE
Strange crash with NEI?

### ISSUE THREAD

**Issue by HyperMan19680** [Nova-Committee/ModernKeyBinding#1]
So it seems when I have the 2.1.0 version going with 1.7.10's NEI 1.0.5.120-universal I get this log and it crashes. Removing NEI is not an option as some of the other mods in the pack require it.

https://paste.ee/p/EBH9b

**Comment by MikhailTapio** [comment]
Use [NEI Unofficial](https://www.curseforge.com/minecraft/mc-mods/notenoughitems-gtnh)(Dependencies: [CodeChickenCore](https://github.com/GTNewHorizons/CodeChickenCore/releases) | [CodeChickenLib](https://github.com/GTNewHorizons/CodeChickenLib/releases)) by GTNH instead.

**Comment by MikhailTapio** [comment]
If nothing else, I'll close this.
I'd also pinned this for it's a common question asked by players.

**Comment by MikhailTapio** [comment]
Btw, [Mixingasm](https://github.com/makamys/Mixingasm) is known to fix this as well.
