### ISSUE TITLE
[Suggestion] Input Types

### ISSUE THREAD

**Issue by xllifi** [Nova-Committee/ModernKeyBinding#13]
Take a look at Helldivers 2 keybinding menu:
<details open=true>
<summary>Image (collapsible)</summary>
<img src="https://github.com/Nova-Committee/ModernKeyBinding/assets/70767436/139db2e0-5d41-4863-b6ad-52a89f949d7e" width=300px/>
</details>

It has input types!! Currently present: 
- Tap. Triggers only when a button is pushed down and released quickly.
- Double Tap. Triggers on the second press if you quickly push down the same button twice.
- Press. Triggers as soon as a button is pushed down.
- Long press. Triggers after a button has been pushed down for a set amount of time.
- Hold. Triggers continuously while a button is being pushed down.

Would love to see this in your mod!

**Comment by MikhailTapio** [comment]
This is usually implemented by the mod that actually uses the keybindings. Out of scope, but yes it's an excellent idea. I'll close and pin :D
