### ISSUE TITLE
Incompatibility with AxolotlClient

### ISSUE THREAD

**Issue by moehreag** [Nova-Committee/ModernKeyBinding#3]
Currently this mod is incompatible with <https://github.com/AxolotlClient/AxolotlClient-mod> (<https://modrinth.com/mod/axolotlclient>) due to this mod overwriting the `setKeyPressed` method:<https://github.com/Nova-Committee/ModernKeyBinding/blob/f2bd97a34eb9cb7ef969f0215fbf94e054359755/src/main/java/committee/nova/mkb/mixin/MixinKeyBinding.java#L157-L166> 

This breaks [this](https://github.com/AxolotlClient/AxolotlClient-mod/blob/685ac2b5f9629a2070e35c265b686f6bdb811d61/1.8.9/src/main/java/io/github/axolotlclient/mixin/KeyBindingMixin.java#L69) mixin respectively.

I hope that a solution to this problem can be found!

Additional Note:\
This repository is currently missing a license.

**Comment by MikhailTapio** [comment]
Okay, I'll make it a HEAD inject soon.
