### ISSUE TITLE
Does not work when Controlling is installed

### ISSUE THREAD

**Issue by MicrocontrollersDev** [Nova-Committee/ModernKeyBinding#5]
Details:
Forge 1.8.9 11.15.1.2318
ModernKeybinding 2.1.0
Controlling 7.0.0.1 (7.0.0.1 is newer than 7.0.0.2. Not sure what's going on there but neither work anyways)

When using the two mods in conjunction, Controlling works fine but ModernKeybinding doesn't do anything. Pressing a modifier will instantly set it to the modifier and won't allow for an extra key.

**Comment by MikhailTapio** [comment]
We already have a "ModernControlling" in our organization repositories. But thx to your issue, I remembered I should post that somewhere like CurseForge.

**Comment by Gamemassa** [comment]
> We've already had a "ModernControlling" in our organization repositories. But thx to your issue, I remembered I should post that somewhere like CurseForge.

I'm noticing that Modern Keybindings does not function correctly with Controlling on Fabric 1.20.x and I'm not sure if that should be here or in its own issue thread, so I decided I'd post it here first and move it later if necessary.

**Comment by MikhailTapio** [comment]
> > We've already had a "ModernControlling" in our organization repositories. But thx to your issue, I remembered I should post that somewhere like CurseForge.
> 
> I'm noticing that Modern Keybindings does not function correctly with Controlling on Fabric 1.20.x and I'm not sure if that should be here or in its own issue thread, so I decided I'd post it here first and move it later if necessary.

Yes. Compatibility for new versions of ModernControlling is not implemented yet.

**Comment by Gamemassa** [comment]
But it is planned?

**Comment by MikhailTapio** [comment]
> But it is planned?

Sure. Maybe a bit later

**Comment by Gamemassa** [comment]
Ok, thanks for confirming.

**Comment by Gamemassa** [comment]
@MikhailTapio Hey Mikhail, I just got a reply from [jaredlll08](https://github.com/jaredlll08) (the developer of Controlling) and he said he's happy to add support code in his mod so you don't have to add it in yours, if that's easier for you.

**Comment by MikhailTapio** [comment]
> @MikhailTapio Hey Mikhail, I just got a reply from [jaredlll08](https://github.com/jaredlll08) (the developer of Controlling) and he said he's happy to add support code (api-related stuff, in his words) in his mod, if that's easier for you.

Hi! I've tried to make a compat, releasing mkb-fabric-1.20.x-1.2.0. Now waiting for Jared to do some stuff on their side.
If you want to use it now:
- Download and install ModernKeyBinding-Fabric-1.20.X-1.2.0
- Download [the modified provider cfg file](https://github.com/Nova-Committee/ModernKeyBinding/releases/download/Fabric-1.20.X-1.2.0/com.blamejared.controlling.platform.IPlatformHelper).
- Open the Controlling jar file with a file archiver(like 7-Zip)
- Copy the provider cfg file you downloaded above and paste it into jarfile\META-INF\services\, overwriting the original file of the same name.
- Launch the game.

**Comment by MikhailTapio** [comment]
I'll close this, anything else to ask plz reopen :D
