### ISSUE TITLE
crash when pressing your sprint keybind

### ISSUE THREAD

**Issue by Candymanmax** [Nova-Committee/ModernKeyBinding#6]
my game crashes when i have the toggle sprint from the accessibility options on and then press my sprint bind.

**Comment by MikhailTapio** [comment]
Please provide the crash report and the latest.log

**Comment by Candymanmax** [comment]
[crash-2023-05-31_16.32.55-client.txt](https://github.com/Nova-Committee/ModernKeyBinding/files/11625592
[2023-05-31-3.log.gz](https://github.com/Nova-Committee/ModernKeyBinding/files/11625595/2023-05-31-3.log.gz)
/crash-2023-05-31_16.32.55-client.txt)

**Comment by Candymanmax** [comment]
my instance is broken so i cant give the lastest.log because its unrelated but thats the log from when it happened

**Comment by MikhailTapio** [comment]
Tried to fix, check [this](https://github.com/Nova-Committee/ModernKeyBinding/releases/tag/Fabric-1.19.4-1.1.0).
It's a bug across versions, so I'll fix the other versions soon one by one.

**Comment by MikhailTapio** [comment]
I'll close this. Any issue, plz reopen :D
