### ISSUE TITLE
We're Almost There Boys!

### ISSUE THREAD

**Issue by jbrown1597** [Nova-Committee/ModernKeyBinding#8]
![12 - Copy](https://github.com/Nova-Committee/ModernKeyBinding/assets/50437670/e70e2c06-ae8c-4be6-9521-0ba832a6ba70)
              > @MikhailTapio Hey Mikhail, I just got a reply from [jaredlll08](https://github.com/jaredlll08) (the developer of Controlling) and he said he's happy to add support code (api-related stuff, in his words) in his mod, if that's easier for you.

Hi! Thx to Jared's help, we've made it. Use Controlling-Fabric-1.20.1-12.0.2(+) & ModernKeyBinding-Fabric-1.20.X-1.2.0(+).

_Originally posted by @MikhailTapio in https://github.com/Nova-Committee/ModernKeyBinding/issues/5#issuecomment-1636966558_
            
________________________

Firstly, you're a god. Thank you for not only making the mod, but being responsive AND helpful. I appreciate you!

Unfortunately, having updated both mods to the versions you specified:
...Now the mods don't necessarily conflict, but they still don't work in conjunction.

_What is fixed:_

- In the bindings menu, I can now successfully set my "modifier + key" in unison as one binding

_What isn't fixed:_

- **In-game, the modifier is ignored and only the key is pressed.**
- Not nearly as important, but in the bindings menu, it *thinks there is confliction, for example, between: "V" and "Alt+V".

**Comment by MikhailTapio** [comment]
Will MKB work when Controlling not installed?

**Comment by jbrown1597** [comment]
I am SO sorry! 
Turns out, it does work. 
I suppose I will leave this thread just incase anyone else is a knucklehead like myself lmao.

I am not sure if it was Connectivity specifically, as I had tried many different mods - but regardless, this is the only mod I need now. 

Thanks again <3
