### ISSUE TITLE
Cannot Bind Only Shift

### ISSUE THREAD

**Issue by Retroactive-Android** [Nova-Committee/ModernKeyBinding#9]
I play Minecraft with shift as sprint and control as crouch (as almost every other game works).
I cannot bind Shift to sprint. Every time I try, it won't exit keybind selection until I press something else. It works if I do like Shift+E, but I cannot bind anything to plain shift. I can even bind to plain Alt, just not shift.

Using Fabric 1.20.X-1.2.0 (I am using it on Quilt so maybe that's the issue? Seems like a design thing to me though).

**Comment by MikhailTapio** [comment]
I'll test on Fabric first.

**Comment by MikhailTapio** [comment]
I am sure it works on Fabric 1.20.2. I'll deploy a Quilt workspace to see if any extra change is needed :D

**Comment by MikhailTapio** [comment]
Uploaded ModernKeyBinding-Quilt-1.0.0+1.20.1.jar on CurseForge. Tested working in dev environment.

**Comment by Retroactive-Android** [comment]
That fixed it! Thank you! :D

**Comment by SanQianQVQ** [comment]
same problem on Fabric 1.20.X-1.2.0
